export const techStacks = {
  "web-development": [
    { name: "HTML5", icon: "html5", theme: { background: "orange-bg" } },
    { name: "CSS", icon: "css3", theme: { background: "blue-bg" } },
    { name: "JavaScript", icon: "javaScript", theme: { background: "yellow-bg" } },
    { name: "React", icon: "react", theme: { background: "teal-flat-bg " } },
    { name: "NodeJs", icon: "nodejs", theme: { background: "green-bg" } },
    { name: "PostgreSQL", icon: "database", theme: { background: "blue-bg" } },
    { name: "Git & Github", icon: "github", theme: { background: "gray-bg" } },
    { name: "VS Code", icon: "vscode", theme: { background: "blue-bg" } },
    { name: "Tailwind CSS", icon: "css3", theme: { background: "teal-flat-bg" } },
    { name: "Figma", icon: "figma", theme: { background: "purple-bg" } },
  ],
  "software-engineering": [
    { name: "JavaScript", icon: "javaScript", theme: { background: "yellow-bg" } },
    { name: "React", icon: "react", theme: { background: "teal-flat-bg " } },
    { name: "NodeJs", icon: "nodejs", theme: { background: "green-bg" } },
    { name: "PostgreSQL", icon: "database", theme: { background: "blue-bg" } },
    { name: "Git & Github", icon: "github", theme: { background: "gray-bg" } },
    { name: "VS Code", icon: "vscode", theme: { background: "blue-bg" } },
    { name: "Figma", icon: "figma", theme: { background: "purple-bg" } },
  ],
  "cybersecurity": [
    { name: "Network Security", icon: "security", theme: { background: "orange-bg" } },
    { name: "Ethical Hacking", icon: "security", theme: { background: "blue-bg" } },
    { name: "Threat Analysis", icon: "security", theme: { background: "yellow-bg" } },
    { name: "PostgreSQL", icon: "database", theme: { background: "blue-bg" } },
    { name: "Git & Github", icon: "github", theme: { background: "gray-bg" } },
    { name: "VS Code", icon: "vscode", theme: { background: "blue-bg" } },
    { name: "Linux Security", icon: "security", theme: { background: "green-bg" } },
  ],
  "data-analytics": [
    { name: "SQL Data", icon: "database", theme: { background: "orange-bg" } },
    { name: "PostgreSQL", icon: "database", theme: { background: "blue-bg" } },
    { name: "Data Viz", icon: "figma", theme: { background: "yellow-bg" } },
    { name: "Git & Github", icon: "github", theme: { background: "gray-bg" } },
    { name: "VS Code", icon: "vscode", theme: { background: "blue-bg" } },
    { name: "Analytical Tools", icon: "nodejs", theme: { background: "green-bg" } },
  ],
  "ui-ux-design": [
    { name: "Figma", icon: "figma", theme: { background: "purple-bg" } },
    { name: "UI Design", icon: "figma", theme: { background: "orange-bg" } },
    { name: "UX Research", icon: "figma", theme: { background: "blue-bg" } },
    { name: "Prototyping", icon: "figma", theme: { background: "yellow-bg" } },
    { name: "VS Code", icon: "vscode", theme: { background: "blue-bg" } },
  ],
  "digital-marketing": [
    { name: "Google Analytics", icon: "google", theme: { background: "blue-bg" } },
    { name: "Meta Ads", icon: "facebook", theme: { background: "blue-bg" } },
    { name: "Canva", icon: "figma", theme: { background: "purple-bg" } },
    { name: "Mailchimp", icon: "email", theme: { background: "yellow-bg" } },
    { name: "SEO Tools", icon: "search", theme: { background: "teal-flat-bg" } },
    { name: "CRM Systems", icon: "handShake", theme: { background: "orange-bg" } },
  ],
  "ai-automation": [
    { name: "OpenAI / LLMs", icon: "brain", theme: { background: "purple-bg" } },
    { name: "Zapier", icon: "automode", theme: { background: "orange-bg" } },
    { name: "Python", icon: "code", theme: { background: "blue-bg" } },
    { name: "Make.com", icon: "autorenew", theme: { background: "purple-bg" } },
    { name: "LangChain", icon: "link", theme: { background: "yellow-bg" } },
    { name: "AI Strategy", icon: "lightBulb", theme: { background: "teal-flat-bg" } },
  ],
  "forex-trading": [
    { name: "MetaTrader 5", icon: "dollarCoin", theme: { background: "blue-bg" } },
    { name: "TradingView", icon: "barChart", theme: { background: "purple-bg" } },
    { name: "Myfxbook", icon: "calendar", theme: { background: "green-bg" } },
    { name: "Risk Calc", icon: "calculator", theme: { background: "orange-bg" } },
    { name: "Economic Cal", icon: "calendar", theme: { background: "blue-bg" } },
    { name: "Psychology Jam", icon: "book", theme: { background: "yellow-bg" } },
  ],
  "mobile-app-development": [
    { name: "Flutter", icon: "mobile", theme: { background: "blue-bg" } },
    { name: "React Native", icon: "react", theme: { background: "teal-flat-bg" } },
    { name: "Dart", icon: "code", theme: { background: "blue-bg" } },
    { name: "Firebase", icon: "cloud", theme: { background: "orange-bg" } },
    { name: "App Store", icon: "rocket", theme: { background: "blue-bg" } },
    { name: "Play Store", icon: "rocket", theme: { background: "green-bg" } },
  ],
  "services": [
    { name: "AWS / Cloud", icon: "cloud", theme: { background: "orange-bg" } },
    { name: "React / Next.js", icon: "react", theme: { background: "teal-flat-bg" } },
    { name: "Node.js", icon: "nodejs", theme: { background: "green-bg" } },
    { name: "PostgreSQL", icon: "database", theme: { background: "blue-bg" } },
    { name: "OpenAI / AI", icon: "brain", theme: { background: "purple-bg" } },
    { name: "Figma Design", icon: "figma", theme: { background: "purple-bg" } },
    { name: "Python", icon: "code", theme: { background: "blue-bg" } },
    { name: "DevOps", icon: "settingsSuggest", theme: { background: "gray-bg" } },
  ],
  "default": [
    { name: "Git & Github", icon: "github", theme: { background: "gray-bg" } },
    { name: "VS Code", icon: "vscode", theme: { background: "blue-bg" } },
  ]
};
