import { Toaster } from "sonner";
import "./globals.css";
import "@/lib/styles/colors.css";

import MainHeader from "@/components/main-header";
import CTASection from "@/components/cta/call-to-action-section";
import Footer from "@/components/footer";
import MainSidebarContextProvider from "@/store/main-sidebar-context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainSidebarContextProvider>
          <MainHeader />
          {children}

          <Footer />
          <Toaster />
        </MainSidebarContextProvider>
      </body>
    </html>
  );
}
